package data;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

public final class Weather {
  private Weather() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WeatherMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WeatherMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional float temperatureF = 1;</code>
     */
    boolean hasTemperatureF();
    /**
     * <code>optional float temperatureF = 1;</code>
     */
    float getTemperatureF();

    /**
     * <code>optional float humidity = 2;</code>
     */
    boolean hasHumidity();
    /**
     * <code>optional float humidity = 2;</code>
     */
    float getHumidity();
  }
  /**
   * Protobuf type {@code WeatherMessage}
   */
  public  static final class WeatherMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WeatherMessage)
      WeatherMessageOrBuilder {
    // Use WeatherMessage.newBuilder() to construct.
    private WeatherMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WeatherMessage() {
      temperatureF_ = 0F;
      humidity_ = 0F;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WeatherMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              temperatureF_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              humidity_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Weather.internal_static_WeatherMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Weather.internal_static_WeatherMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Weather.WeatherMessage.class, Weather.WeatherMessage.Builder.class);
    }

    private int bitField0_;
    public static final int TEMPERATUREF_FIELD_NUMBER = 1;
    private float temperatureF_;
    /**
     * <code>optional float temperatureF = 1;</code>
     */
    public boolean hasTemperatureF() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional float temperatureF = 1;</code>
     */
    public float getTemperatureF() {
      return temperatureF_;
    }

    public static final int HUMIDITY_FIELD_NUMBER = 2;
    private float humidity_;
    /**
     * <code>optional float humidity = 2;</code>
     */
    public boolean hasHumidity() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional float humidity = 2;</code>
     */
    public float getHumidity() {
      return humidity_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, temperatureF_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, humidity_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, temperatureF_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, humidity_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Weather.WeatherMessage)) {
        return super.equals(obj);
      }
      Weather.WeatherMessage other = (Weather.WeatherMessage) obj;

      boolean result = true;
      result = result && (hasTemperatureF() == other.hasTemperatureF());
      if (hasTemperatureF()) {
        result = result && (
            Float.floatToIntBits(getTemperatureF())
            == Float.floatToIntBits(
                other.getTemperatureF()));
      }
      result = result && (hasHumidity() == other.hasHumidity());
      if (hasHumidity()) {
        result = result && (
            Float.floatToIntBits(getHumidity())
            == Float.floatToIntBits(
                other.getHumidity()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasTemperatureF()) {
        hash = (37 * hash) + TEMPERATUREF_FIELD_NUMBER;
        hash = (53 * hash) + Float.floatToIntBits(
            getTemperatureF());
      }
      if (hasHumidity()) {
        hash = (37 * hash) + HUMIDITY_FIELD_NUMBER;
        hash = (53 * hash) + Float.floatToIntBits(
            getHumidity());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Weather.WeatherMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Weather.WeatherMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Weather.WeatherMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Weather.WeatherMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Weather.WeatherMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Weather.WeatherMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Weather.WeatherMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Weather.WeatherMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Weather.WeatherMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Weather.WeatherMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Weather.WeatherMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WeatherMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WeatherMessage)
        Weather.WeatherMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Weather.internal_static_WeatherMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Weather.internal_static_WeatherMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Weather.WeatherMessage.class, Weather.WeatherMessage.Builder.class);
      }

      // Construct using weather.messages.Weather.WeatherMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        temperatureF_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        humidity_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Weather.internal_static_WeatherMessage_descriptor;
      }

      public Weather.WeatherMessage getDefaultInstanceForType() {
        return Weather.WeatherMessage.getDefaultInstance();
      }

      public Weather.WeatherMessage build() {
        Weather.WeatherMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Weather.WeatherMessage buildPartial() {
        Weather.WeatherMessage result = new Weather.WeatherMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.temperatureF_ = temperatureF_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.humidity_ = humidity_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Weather.WeatherMessage) {
          return mergeFrom((Weather.WeatherMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Weather.WeatherMessage other) {
        if (other == Weather.WeatherMessage.getDefaultInstance()) return this;
        if (other.hasTemperatureF()) {
          setTemperatureF(other.getTemperatureF());
        }
        if (other.hasHumidity()) {
          setHumidity(other.getHumidity());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Weather.WeatherMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Weather.WeatherMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float temperatureF_ ;
      /**
       * <code>optional float temperatureF = 1;</code>
       */
      public boolean hasTemperatureF() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional float temperatureF = 1;</code>
       */
      public float getTemperatureF() {
        return temperatureF_;
      }
      /**
       * <code>optional float temperatureF = 1;</code>
       */
      public Builder setTemperatureF(float value) {
        bitField0_ |= 0x00000001;
        temperatureF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float temperatureF = 1;</code>
       */
      public Builder clearTemperatureF() {
        bitField0_ = (bitField0_ & ~0x00000001);
        temperatureF_ = 0F;
        onChanged();
        return this;
      }

      private float humidity_ ;
      /**
       * <code>optional float humidity = 2;</code>
       */
      public boolean hasHumidity() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional float humidity = 2;</code>
       */
      public float getHumidity() {
        return humidity_;
      }
      /**
       * <code>optional float humidity = 2;</code>
       */
      public Builder setHumidity(float value) {
        bitField0_ |= 0x00000002;
        humidity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float humidity = 2;</code>
       */
      public Builder clearHumidity() {
        bitField0_ = (bitField0_ & ~0x00000002);
        humidity_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WeatherMessage)
    }

    // @@protoc_insertion_point(class_scope:WeatherMessage)
    private static final Weather.WeatherMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Weather.WeatherMessage();
    }

    public static Weather.WeatherMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<WeatherMessage>
        PARSER = new com.google.protobuf.AbstractParser<WeatherMessage>() {
      public WeatherMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new WeatherMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WeatherMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<WeatherMessage> getParserForType() {
      return PARSER;
    }

    public Weather.WeatherMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WeatherMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WeatherMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rweather.proto\"8\n\016WeatherMessage\022\024\n\014tem" +
      "peratureF\030\001 \001(\002\022\020\n\010humidity\030\002 \001(\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_WeatherMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WeatherMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WeatherMessage_descriptor,
        new String[] { "TemperatureF", "Humidity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
